import time

print("| |       | |  |  |   |||       |||")
time.sleep(0.2)
print("| |       | |  |--|   |||       |||")
time.sleep(0.2)
print("| |_______| |  |  |")
time.sleep(0.2)
print("|           |  |  |   |||       |||")
time.sleep(0.2)
print("| |-------| |  |  |   |||       |||")
time.sleep(0.2)
print("| |       | |  |  |      |||||||")
time.sleep(0.2)
print("| |       | |  |  |")
time.sleep(0.6)

print("--------------------------------------+")
time.sleep(0.5)
print("CALCULATE AN AREA USING PYTHON!")
time.sleep(1)
print("x_____________x")
time.sleep(0.1) 
print("| \\            \\")
time.sleep(0.1)
print("|  \\            \\")
time.sleep(0.1)
print("|  |-------------|")
time.sleep(0.1)
print("|  |             |")
time.sleep(0.1)
print("|  |             |")
time.sleep(0.1)
print("x  |          x  |")
time.sleep(0.1)
print(" \\________________")
time.sleep(0.1)
print("Pedro Marugi's first project.")
time.sleep(1)
print("--------------------------------------+")
time.sleep(0.3)
base = int(input("Insert base: "))
altura = int(input("Insert height: "))
multiplicacao = (base * altura)
print("--------------------------------------+")
time.sleep(0.3)
print("calculating...")
time.sleep(2)
print("--------------------------------------+")
time.sleep(0.3)
print(f"THE AREA IS {multiplicacao}.")
time.sleep(3)
print("--------------------------------------+")
time.sleep(0.3)
print("Closing session...")
time.sleep(2)
print("--------------------------------------+")
time.sleep(0.3)
print("|-----------------|")
time.sleep(0.2)
print("|                 |")
time.sleep(0.2)
print("|______     ______|")
time.sleep(0.2)
print("      |     |      ")
time.sleep(0.2)
print("      |     |      ")
time.sleep(0.2)
print("      |     |      ")
time.sleep(0.2)
print("      |     |      ")
time.sleep(0.2)
print("      |     |      ")
time.sleep(0.2)
print("      |     |      ")
time.sleep(0.2)
print("------|_____|------")
time.sleep(0.2)
print("|     |     |     |")
time.sleep(0.2)
print("|     |     |     |")
time.sleep(0.2)
print("|     |     |     |")
time.sleep(0.2)
print("|     |-----|     |")
time.sleep(0.2)
print("|                 |")
time.sleep(0.2)
print("|      _____      |")
time.sleep(0.2)
print("|     |     |     |")
time.sleep(0.2)
print("|     |     |     |")
time.sleep(0.2)
print("|-----|     |-----|")
time.sleep(0.2)
print("|     |     |     |")
time.sleep(0.2)
print("|__   |     |   __|")
time.sleep(0.2)
print("  |     | |     |  ")
time.sleep(0.2)
print("  |__   | |   __|  ")
time.sleep(0.2)
print("     |   -   |     ")
time.sleep(0.2)
print("   __|   _   |__   ")
time.sleep(0.2)
print("  |     | |     |  ")
time.sleep(0.2)
print("__|     | |     |__")
time.sleep(0.2)
print("|     |     |     |")
time.sleep(0.2)
print("|-----|_____|-----|")
time.sleep(0.2)
print("     |       |     ")
time.sleep(0.2)
print("     |       |     ")
time.sleep(0.2)
print("     |       |     ")
time.sleep(0.2)
print("     |       |     ")
time.sleep(0.2)
print("     |       |     ")
time.sleep(0.2)
print("     |-------|     ")
time.sleep(0.2)
print("      _______      ")
time.sleep(0.2)
print("     |       |     ")
time.sleep(0.2)
print("     |_______|     ")
time.sleep(0.2)
print("                   ")
time.sleep(0.2)
print("                   ")
time.sleep(0.2)
print("                   ")
time.sleep(0.2)
print("                   ")
time.sleep(0.2)
print("                   ")
time.sleep(0.2)
print("                   ")
time.sleep(0.2)
print("                   ")
time.sleep(0.2)
print("                   ")
time.sleep(0.2)
print("                   ")
time.sleep(0.2)
print("                   ")
time.sleep(0.2)
print("                   ")
time.sleep(0.2)
print("                   ")
time.sleep(0.2)
print("                   ")
time.sleep(0.2)
print("                   ")
time.sleep(0.2)
print("                   ")
time.sleep(0.2)
print("                   ")
time.sleep(0.2)
print("                   ")
time.sleep(0.2)
print("                   ")
time.sleep(0.2)

