CREATE TABLE DISCIPLINA (
    CODIGO_DISCIPLINA VARCHAR2(5) PRIMARY KEY,
    DESCRICAO         VARCHAR2(50) NOT NULL
);
CREATE TABLE PROFESSOR (
    CODIGO             NUMBER        PRIMARY KEY,
    NOME               VARCHAR2(100) NOT NULL,
    CODIGO_DISCIPLINA  VARCHAR2(555)   NOT NULL,
    CONSTRAINT FK_PROFESSOR_DISCIPLINA FOREIGN KEY (CODIGO_DISCIPLINA)
        REFERENCES DISCIPLINA (CODIGO_DISCIPLINA)
);
CREATE TABLE TURMA (
    CODIGO      VARCHAR2(10) PRIMARY KEY,
    NOME_TURMA  VARCHAR2(50)    NOT NULL
);
CREATE TABLE ALUNO (
    CODIGO   NUMBER      PRIMARY KEY,
    NOME     VARCHAR2(100) NOT NULL,
    IDADE    NUMBER(2)     NOT NULL,
    TURMA    VARCHAR2(100)  NOT NULL,
    CONSTRAINT FK_ALUNO_TURMA FOREIGN KEY (TURMA)
        REFERENCES TURMA (CODIGO)
);
INSERT INTO DISCIPLINA (CODIGO_DISCIPLINA, DESCRICAO)
VALUES ('BD', 'Banco de Dados');
INSERT INTO DISCIPLINA (CODIGO_DISCIPLINA, DESCRICAO)
VALUES ('EN', 'Inglês');

INSERT INTO PROFESSOR (CODIGO, NOME, CODIGO_DISCIPLINA)
VALUES(1, 'Charles Caleiro', 'BD');
INSERT INTO PROFESSOR (CODIGO, NOME, CODIGO_DISCIPLINA)
VALUES(2, 'Tiago Vieira', 'EN');

INSERT INTO TURMA(CODIGO, NOME_TURMA) VALUES ('701MAT', 'Sétima Série Um Matutino');
INSERT INTO TURMA(CODIGO, NOME_TURMA) VALUES ('702VES', 'Sétima Série Dois Vespertino');
INSERT INTO TURMA(CODIGO, NOME_TURMA) VALUES ('801MAT', 'Oitava Série Um Matutino');
INSERT INTO TURMA(CODIGO, NOME_TURMA) VALUES ('802VES', 'Oitava Série Dois Vespertino');
INSERT INTO TURMA(CODIGO, NOME_TURMA) VALUES ('901MAT', 'Nona Série Um Matutino');
INSERT INTO TURMA(CODIGO, NOME_TURMA) VALUES ('902VES', 'Nona Série Dois Vespertino');
INSERT INTO TURMA(CODIGO, NOME_TURMA) VALUES ('101INFO', 'Primeiro Ano Um Técnico em Informática');
INSERT INTO TURMA(CODIGO, NOME_TURMA) VALUES ('102LOG', 'Primeiro Ano Dois Técnico em Logística');
INSERT INTO TURMA(CODIGO, NOME_TURMA) VALUES ('104LOG', 'Primeiro Ano Quatro Técnico em Logística');
INSERT INTO TURMA(CODIGO, NOME_TURMA) VALUES ('106INFO', 'Primeiro Ano Seis Técnico em Informática');
INSERT INTO TURMA(CODIGO, NOME_TURMA) VALUES ('201SST', 'Segundo Ano Um Técnico em Segurança do Trabalho');
INSERT INTO TURMA(CODIGO, NOME_TURMA) VALUES ('201EDF', 'Segundo Ano Um Técnico em Edificações');
INSERT INTO TURMA(CODIGO, NOME_TURMA) VALUES ('202INFO', 'Segundo Ano Dois Técnico em Informática');
INSERT INTO TURMA(CODIGO, NOME_TURMA) VALUES ('301POR', 'Terceiro Ano Um Técnico em Portos');
INSERT INTO TURMA(CODIGO, NOME_TURMA) VALUES ('302EDF', 'Terceiro Ano Dois Técnico em Edificações');

INSERT INTO ALUNO (CODIGO, NOME, IDADE, TURMA) VALUES (1, 'GABRIEL SOUZA',13,'701MAT');
INSERT INTO ALUNO (CODIGO, NOME, IDADE, TURMA) VALUES (2, 'ANA BEATRIZ LIMA',13,'702MAT');
INSERT INTO ALUNO (CODIGO, NOME, IDADE, TURMA) VALUES (3, 'LUCAS OLIVEIRA',14,'801MAT');
INSERT INTO ALUNO (CODIGO, NOME, IDADE, TURMA) VALUES (4, 'MARIA EDUARDA SANTOS',14,'802VES');
INSERT INTO ALUNO (CODIGO, NOME, IDADE, TURMA) VALUES (5, 'PEDRO HENRIQUE COSTA',15,'901MAT');
INSERT INTO ALUNO (CODIGO, NOME, IDADE, TURMA) VALUES (6, 'ISABELA FERREIRA',15,'902VES');
INSERT INTO ALUNO (CODIGO, NOME, IDADE, TURMA) VALUES (7, 'MATHEUS ALMEIDA',15,'101INFO');
INSERT INTO ALUNO (CODIGO, NOME, IDADE, TURMA) VALUES (8, 'SOPHIA RODRIGUES',16,'102LOG');
INSERT INTO ALUNO (CODIGO, NOME, IDADE, TURMA) VALUES (9, 'GUILHERME PEREIRA',16,'104LOG');
INSERT INTO ALUNO (CODIGO, NOME, IDADE, TURMA) VALUES (10, 'LAURA MARTINA',16,'106INFO');
INSERT INTO ALUNO (CODIGO, NOME, IDADE, TURMA) VALUES (11, 'RAFAEL CARVALHO',16,'201SST');
INSERT INTO ALUNO (CODIGO, NOME, IDADE, TURMA) VALUES (12, 'JULIA GOMES',17,'201EDF');
INSERT INTO ALUNO (CODIGO, NOME, IDADE, TURMA) VALUES (13, 'BRUNO RIBEIRO',17,'201INFO');
INSERT INTO ALUNO (CODIGO, NOME, IDADE, TURMA) VALUES (14, 'BEATRIZ BARBOSA',17,'301POR');
INSERT INTO ALUNO (CODIGO, NOME, IDADE, TURMA) VALUES (15, 'ENZO ARAÚJO',18,'302EDF');
INSERT INTO ALUNO (CODIGO, NOME, IDADE, TURMA) VALUES (16, 'MANUELA DIAS',13,'701MAT');
INSERT INTO ALUNO (CODIGO, NOME, IDADE, TURMA) VALUES (17, 'Miguel Nascimento',13,'702MAT');
INSERT INTO ALUNO (CODIGO, NOME, IDADE, TURMA) VALUES (18, 'Alice Monteiro',14,'801MAT');
INSERT INTO ALUNO (CODIGO, NOME, IDADE, TURMA) VALUES (19, 'Davi Cardoso',14,'802VES');
INSERT INTO ALUNO (CODIGO, NOME, IDADE, TURMA) VALUES (20, 'Valentina Teixeira',15,'901MAT');
INSERT INTO ALUNO (CODIGO, NOME, IDADE, TURMA) VALUES (21, 'Arthur Correia',15,'902VES');
INSERT INTO ALUNO (CODIGO, NOME, IDADE, TURMA) VALUES (22, 'Lorena Pinto',15,'101INFO');
INSERT INTO ALUNO (CODIGO, NOME, IDADE, TURMA) VALUES (23, 'Heitor Moreira',16,'102LOG');
INSERT INTO ALUNO (CODIGO, NOME, IDADE, TURMA) VALUES (24, 'Yasmin Cavalcante',16,'104LOG');
INSERT INTO ALUNO (CODIGO, NOME, IDADE, TURMA) VALUES (25, 'Theo Rocha',16,'106INFO');
INSERT INTO ALUNO (CODIGO, NOME, IDADE, TURMA) VALUES (26, 'Helena Batista',16,'201SST');
INSERT INTO ALUNO (CODIGO, NOME, IDADE, TURMA) VALUES (27, 'Bernardo Freitas',17,'202INFO');
INSERT INTO ALUNO (CODIGO, NOME, IDADE, TURMA) VALUES (28, 'Lívia Nunes',17,'301POR');
INSERT INTO ALUNO (CODIGO, NOME, IDADE, TURMA) VALUES (29, 'Vinicius Machado',17,'302EDF');
INSERT INTO ALUNO (CODIGO, NOME, IDADE, TURMA) VALUES (30, 'Larissa Reis',18,'302EDF');
INSERT INTO ALUNO (CODIGO, NOME, IDADE, TURMA) VALUES (31, 'Gustavo Azevedo',13,'701MAT');
INSERT INTO ALUNO (CODIGO, NOME, IDADE, TURMA) VALUES (32, 'Camila Vieira',13,'702MAT');
INSERT INTO ALUNO (CODIGO, NOME, IDADE, TURMA) VALUES (33, 'Felipe Duarte',14,'801MAT');
INSERT INTO ALUNO (CODIGO, NOME, IDADE, TURMA) VALUES (34, 'Amanda Farias',14,'802VES');
INSERT INTO ALUNO (CODIGO, NOME, IDADE, TURMA) VALUES (35, 'Leonardo Campos',15,'901MAT');
INSERT INTO ALUNO (CODIGO, NOME, IDADE, TURMA) VALUES (36, 'Bianca Xavier',15,'902VES');
INSERT INTO ALUNO (CODIGO, NOME, IDADE, TURMA) VALUES (37, 'Caio Fonseca',15,'101INFO');
INSERT INTO ALUNO (CODIGO, NOME, IDADE, TURMA) VALUES (38, 'Fernanda Melo',16,'102LOG');
INSERT INTO ALUNO (CODIGO, NOME, IDADE, TURMA) VALUES (39, 'João Vitor Tavares',16,'104LOG');
INSERT INTO ALUNO (CODIGO, NOME, IDADE, TURMA) VALUES (40, 'Rebeca Andrade',16,'106INFO');
