CREATE TABLE DISCIPLINA (
    CODIGO_DISCIPLINA VARCHAR2(5) PRIMARY KEY,
    DESCRICAO         VARCHAR2(50) NOT NULL
);

CREATE TABLE PROFESSOR (
    CODIGO             NUMBER        PRIMARY KEY,
    NOME               VARCHAR2(100) NOT NULL,
    CODIGO_DISCIPLINA  VARCHAR2(5)   NOT NULL,
    CODIGO_DISCIPLINA  VARCHAR2(5)   NOT NULL,
    CONSTRAINT FK_PROFESSOR_DISCIPLINA FOREIGN KEY (CODIGO_DISCIPLINA)
        REFERENCES DISCIPLINA (CODIGO DISCIPLINA)
);

CREATE TABLE TURMA (
    CODIGO      VARCHAR2(10) PRIMARY KEY,
    NOME_TURMA  VARCHAR2(5)  NOT NULL,
);

CREATE TABLE ALUNO (
    CODIGO   NUMBER      PRIMARY KEY,
    NOME     VARCHAR2(100) NOT NULL,
    IDADE    NUMBER(2)     NOT NULL,
    TURMA    VARCHAR2(10)  NOT NULL,
    CONSTRAINT FK_ALUNO_TURMA FOREIGN KEY (TURMA)
        REFERENCES TURMA (CODIGO)
);

INSERT INTO DISCIPLINA (CODIGO_DISCIPLINA, DESCRICAO)
VALUES ('BD', 'Banco de Dados');
INSERT INTO DISCIPLINA (CODIGO_DISCIPLINA, DESCRICAO)
VALUES ('EN', 'Inglês');

INSERT INTO PROFESSOR (CODIGO, NOME, CODIGO_DISCIPLINA)
VALUES(1, 'Charles Caleiro', 'BD');
INSERT INTO PROFESSOR (CODIGO, NOME, CODIGO_DISCIPLINA)
VALUES(2, 'Tiago Vieira', 'EN');

INSERT INTO TURMA(CODIGO, NOME_TURMA) VALUES ('701MAT', 'Sétima Série Um Matutino');
INSERT INTO TURMA(CODIGO, NOME_TURMA) VALUES ('702VES', 'Sétima Série Dois Vespertino');
INSERT INTO TURMA(CODIGO, NOME_TURMA) VALUES ('801MAT', 'Oitava Série Um Matutino');
INSERT INTO TURMA(CODIGO, NOME_TURMA) VALUES ('802VES', 'Oitava Série Dois Vespertino');
INSERT INTO TURMA(CODIGO, NOME_TURMA) VALUES ('901MAT', 'Nona Série Um Matutino');
INSERT INTO TURMA(CODIGO, NOME_TURMA) VALUES ('902VES', 'Nona Série Dois Vespertino');
INSERT INTO TURMA(CODIGO, NOME_TURMA) VALUES ('101INFO', 'Primeiro Ano Um Técnico em Informática');
