CREATE TABLE DISCIPLINA (
    CODIGO_DISCIPLINA VARCHAR2(5) PRIMARY KEY,
    DESCRICAO         VARCHAR2(50) NOT NULL
);

CREATE TABLE PROFESSOR (
    CODIGO             NUMBER        PRIMARY KEY,
    NOME               VARCHAR2(100) NOT NULL,
    CODIGO_DISCIPLINA  VARCHAR2(5)   NOT NULL,
    CODIGO_DISCIPLINA  VARCHAR2(5)   NOT NULL,
    CONSTRAINT FK_PROFESSOR_DISCIPLINA FOREIGN KEY (CODIGO_DISCIPLINA)
        REFERENCES DISCIPLINA (CODIGO DISCIPLINA)
);

CREATE TABLE TURMA (
    CODIGO      VARCHAR2(10) PRIMARY KEY,
    NOME_TURMA  VARCHAR2(5)  NOT NULL,
);

CREATE TABLE ALUNO (
    CODIGO   NUMBER      PRIMARY KEY,
    NOME     VARCHAR2(100) NOT NULL,
    IDADE    NUMBER(2)     NOT NULL,
    TURMA    VARCHAR2(10)  NOT NULL,
    CONSTRAINT FK_ALUNO_TURMA FOREIGN KEY (TURMA)
        REFERENCES TURMA (CODIGO)
);
